name: Rust fmt + clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # see https://github.com/marketplace/actions/checkout-submodules
      with:
        submodules: recursive
    - name: Check
      run: cargo check --verbose
    - name: fmt
      run: cargo fmt --check --all
    - name: clippy
      run: cargo clippy
