name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3 # see https://github.com/marketplace/actions/checkout-submodules
      with:
        submodules: recursive
    - uses: extractions/setup-just@v4
    - name: Check
      run: just ci-check
    - name: Test
      run: just ci-test
    - name: Format
      run: just ci-formatted
    - name: Clippy
      run: just ci-clippy
    - name: Build documentation
      run: just ci-docs
